source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
pod 'GoogleMaps'

source 'https://github.com/CocoaPods/Specs.git'
pod 'AWSCore'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSMobileAnalytics'
pod 'AWSS3'
pod 'AWSCognito'